import { expect, test } from '@jest/globals'
import type { ViewModel } from '../src/parts/ViewModel/ViewModel.ts'

test('ViewModel includes the chat rendering state required by chat-view', () => {
  const viewModel = {
    addContextButtonEnabled: true,
    agentMode: 'agent',
    agentModePickerOpen: false,
    authEnabled: true,
    authErrorMessage: '',
    chatListScrollTop: 0,
    composerAttachmentPreviewOverlayAttachmentId: '',
    composerAttachmentPreviewOverlayError: false,
    composerAttachments: [],
    composerDropActive: false,
    composerDropEnabled: true,
    composerFontFamily: 'monospace',
    composerFontSize: 13,
    composerHeight: 42,
    composerLineHeight: 20,
    composerValue: 'hello',
    gitBranches: [{ current: true, name: 'main' }],
    gitBranchPickerErrorMessage: '',
    gitBranchPickerOpen: false,
    gitBranchPickerVisible: true,
    hasSpaceForAgentModePicker: true,
    hasSpaceForRunModePicker: true,
    listFocusedIndex: 0,
    listFocusOutline: false,
    messagesAutoScrollEnabled: true,
    messagesScrollTop: 0,
    modelPickerOpen: false,
    modelPickerSearchValue: '',
    models: [{ id: 'gpt-test', name: 'GPT Test' }],
    openApiApiKeyInput: '',
    openApiApiKeyInputPattern: '.*',
    openApiApiKeysSettingsUrl: 'https://example.com/settings',
    openApiApiKeyState: 'idle',
    openRouterApiKeyInput: '',
    openRouterApiKeyState: 'saving',
    parsedMessages: [{ id: '1', parsedContent: [], text: 'hello' }],
    projectExpandedIds: ['project-1'],
    projectListScrollTop: 0,
    projects: [{ id: 'project-1', name: 'Workspace', uri: 'file:///workspace' }],
    reasoningEffort: 'medium',
    reasoningEffortPickerOpen: false,
    reasoningPickerEnabled: true,
    runMode: 'local',
    runModePickerOpen: false,
    scrollDownButtonEnabled: false,
    searchEnabled: true,
    searchFieldVisible: false,
    searchValue: '',
    selectChevronEnabled: true,
    selectedModelId: 'gpt-test',
    selectedProjectId: 'project-1',
    selectedSessionId: 'session-1',
    sessions: [{ id: 'session-1', messages: [], title: 'Session' }],
    showChatListTime: true,
    showRunMode: true,
    todoListToolEnabled: true,
    tokensMax: 1000,
    tokensUsed: 100,
    usageOverviewEnabled: true,
    useChatMathWorker: false,
    useModelWorker: false,
    userName: 'Simon',
    userState: 'loggedIn',
    viewMode: 'detail',
    visibleModels: [{ id: 'gpt-test', name: 'GPT Test' }],
    voiceDictationEnabled: false,
  } satisfies ViewModel

  expect(viewModel.selectedSessionId).toBe('session-1')
})
