import type { ChatState } from '../ChatState/ChatState.ts'
import * as Strings from '../ChatStrings/ChatStrings.ts'
import { defaultChatFocusSidebarWidth } from '../GetClampedChatFocusSidebarWidth/GetClampedChatFocusSidebarWidth.ts'
import { getDefaultModels } from '../GetDefaultModels/GetDefaultModels.ts'
import { getDefaultSystemPrompt } from '../GetDefaultSystemPrompt/GetDefaultSystemPrompt.ts'
import { getModelPickerHeight } from '../GetModelPickerHeight/GetModelPickerHeight.ts'
import { getVisibleModels } from '../GetVisibleModels/GetVisibleModels.ts'

export const createDefaultState = (): ChatState => {
  const defaultProjectId = 'project-1'
  const defaultSessionId = 'session-1'
  const defaultModelId = 'test'
  const modelPickerHeaderHeight = 40
  const chatMessageFontSize = 13
  const chatMessageLineHeight = 20
  const composerFontSize = 13
  const composerLineHeight = 20
  const models = getDefaultModels()
  const visibleModels = getVisibleModels(models, '')
  return {
    addContextButtonEnabled: false,
    aiSessionTitleGenerationEnabled: false,
    assetDir: '',
    authAccessToken: '',
    authEnabled: false,
    authErrorMessage: '',
    authRefreshToken: '',
    authStatus: 'signed-out',
    backendUrl: '',
    chatFocusSidebarResizeActive: false,
    chatFocusSidebarResizeStartWidth: defaultChatFocusSidebarWidth,
    chatFocusSidebarResizeStartX: 0,
    chatFocusSidebarWidth: defaultChatFocusSidebarWidth,
    chatHistoryEnabled: true,
    chatInputHistory: [],
    chatInputHistoryDraft: '',
    chatInputHistoryIndex: -1,
    chatListScrollTop: 0,
    chatMessageFontFamily: 'system-ui',
    chatMessageFontSize,
    chatMessageLineHeight,
    chatSendAreaPaddingBottom: 10,
    chatSendAreaPaddingLeft: 8,
    chatSendAreaPaddingRight: 8,
    chatSendAreaPaddingTop: 10,
    composerDropActive: false,
    composerDropEnabled: true,
    composerFontFamily: 'system-ui',
    composerFontSize,
    composerHeight: composerLineHeight + 8,
    composerLineHeight,
    composerSelectionEnd: 0,
    composerSelectionStart: 0,
    composerValue: '',
    emitStreamingFunctionCallEvents: false,
    errorCount: 0,
    focus: 'composer',
    focused: false,
    headerHeight: 50,
    height: 0,
    initial: true,
    inputSource: 'script',
    lastNormalViewMode: 'list',
    lastSubmittedSessionId: '',
    listFocusedIndex: -1,
    listItemHeight: 40,
    maxComposerRows: 5,
    maxToolCalls: 10,
    messagesAutoScrollEnabled: true,
    messagesScrollTop: 0,
    mockAiResponseDelay: 800,
    mockApiCommandId: '',
    modelPickerHeaderHeight,
    modelPickerHeight: getModelPickerHeight(modelPickerHeaderHeight, visibleModels.length),
    modelPickerListScrollTop: 0,
    modelPickerOpen: false,
    modelPickerSearchValue: '',
    models,
    nextMessageId: 1,
    openApiApiBaseUrl: 'https://api.openai.com/v1',
    openApiApiKey: '',
    openApiApiKeyInput: '',
    openApiApiKeyInputPattern: '^sk-.+',
    openApiApiKeysSettingsUrl: 'https://platform.openai.com/api-keys',
    openApiApiKeyState: 'idle',
    openRouterApiBaseUrl: 'https://openrouter.ai/api/v1',
    openRouterApiKey: '',
    openRouterApiKeyInput: '',
    openRouterApiKeysSettingsUrl: 'https://openrouter.ai/settings/keys',
    openRouterApiKeyState: 'idle',
    parsedMessages: [],
    passIncludeObfuscation: false,
    platform: 0,
    projectExpandedIds: [defaultProjectId],
    projectListScrollTop: 0,
    projects: [
      {
        id: defaultProjectId,
        name: '_blank',
        uri: '',
      },
    ],
    questionToolEnabled: false,
    renamingSessionId: '',
    runMode: 'local',
    runModePickerOpen: false,
    searchEnabled: false,
    searchFieldVisible: false,
    searchValue: '',
    selectedModelId: defaultModelId,
    selectedProjectId: defaultProjectId,
    selectedSessionId: defaultSessionId,
    sessions: [
      {
        id: defaultSessionId,
        messages: [],
        projectId: defaultProjectId,
        title: Strings.defaultSessionTitle(),
      },
    ],
    showRunMode: true,
    streamingEnabled: true,
    systemPrompt: getDefaultSystemPrompt(),
    textAreaPaddingBottom: 0,
    textAreaPaddingLeft: 12,
    textAreaPaddingRight: 12,
    textAreaPaddingTop: 0,
    todoListToolEnabled: false,
    tokensMax: 0,
    tokensUsed: 0,
    uid: 0,
    usageOverviewEnabled: false,
    useChatCoordinatorWorker: false,
    useChatMathWorker: true,
    useChatMessageParsingWorker: false,
    useChatNetworkWorkerForRequests: false,
    useChatToolWorker: true,
    useMockApi: false,
    userName: '',
    userSubscriptionPlan: '',
    userUsedTokens: 0,
    viewMode: 'list',
    visibleModels,
    voiceDictationEnabled: false,
    warningCount: 0,
    webSearchEnabled: true,
    width: 0,
    x: 0,
    y: 0,
  }
}
