import { ViewletCommand } from '@lvce-editor/constants'
import type { ChatState } from '../ChatState/ChatState.ts'
import { getChatVirtualDom } from '../GetChatViewDom/GetChatViewDom.ts'

export const renderItems = (oldState: ChatState, newState: ChatState): any => {
  const {
    authEnabled,
    authErrorMessage,
    authStatus,
    chatListScrollTop,
    composerDropActive,
    composerDropEnabled,
    composerFontFamily,
    composerFontSize,
    composerHeight,
    composerLineHeight,
    composerValue,
    initial,
    messagesScrollTop,
    models,
    openApiApiKeyInput,
    openRouterApiKeyInput,
    openRouterApiKeyState,
    parsedMessages,
    projectExpandedIds,
    projectListScrollTop,
    projects,
    runMode,
    selectedModelId,
    selectedProjectId,
    selectedSessionId,
    sessions,
    showRunMode,
    tokensMax,
    tokensUsed,
    uid,
    usageOverviewEnabled,
    useChatMathWorker,
    viewMode,
    voiceDictationEnabled,
  } = newState
  if (initial) {
    return [ViewletCommand.SetDom2, uid, []]
  }
<<<<<<< HEAD
  const dom = getChatVirtualDom(
    sessions,
    selectedSessionId,
    composerValue,
    openRouterApiKeyInput,
    viewMode,
    models,
    selectedModelId,
    usageOverviewEnabled,
    showRunMode,
    runMode,
    tokensUsed,
    tokensMax,
    openApiApiKeyInput,
    openRouterApiKeyState,
    composerHeight,
    composerFontSize,
    composerFontFamily,
    composerLineHeight,
=======
  const dom = getChatVirtualDom({
    authEnabled,
    authErrorMessage,
    authStatus,
>>>>>>> origin/main
    chatListScrollTop,
    composerDropActive,
    composerDropEnabled,
    composerFontFamily,
    composerFontSize,
    composerHeight,
    composerLineHeight,
    composerValue,
    messagesScrollTop,
    models,
    openApiApiKeyInput,
    openRouterApiKeyInput,
    openRouterApiKeyState,
    parsedMessages,
    projectExpandedIds,
    projectListScrollTop,
    projects,
    selectedModelId,
    selectedProjectId,
    selectedSessionId,
    sessions,
    tokensMax,
    tokensUsed,
    usageOverviewEnabled,
    useChatMathWorker,
    viewMode,
    voiceDictationEnabled,
  })
  return [ViewletCommand.SetDom2, uid, dom]
}
