import { ViewletCommand } from '@lvce-editor/constants'
import type { ChatState } from '../ChatState/ChatState.ts'
import { getChatVirtualDom } from '../GetChatViewDom/GetChatViewDom.ts'

export const renderItems = (oldState: ChatState, newState: ChatState): any => {
  const {
    addContextButtonEnabled,
    authEnabled,
    authErrorMessage,
    authStatus,
    chatListScrollTop,
    composerDropActive,
    composerDropEnabled,
    composerFontFamily,
    composerFontSize,
    composerHeight,
    composerLineHeight,
    composerValue,
    initial,
    listFocusedIndex,
    messagesScrollTop,
    modelPickerOpen,
    modelPickerSearchValue,
    models,
    openApiApiKeyInput,
    openApiApiKeyInputPattern,
    openApiApiKeysSettingsUrl,
    openApiApiKeyState,
    openRouterApiKeyInput,
    openRouterApiKeyState,
    parsedMessages,
    projectExpandedIds,
    projectListScrollTop,
    projects,
    runMode,
    runModePickerOpen,
    searchEnabled,
    searchFieldVisible,
    searchValue,
    selectedModelId,
    selectedProjectId,
    selectedSessionId,
    sessions,
    showRunMode,
    todoListToolEnabled,
    tokensMax,
    tokensUsed,
    uid,
    usageOverviewEnabled,
    useChatMathWorker,
    viewMode,
    visibleModels,
    voiceDictationEnabled,
  } = newState
  if (initial) {
    return [ViewletCommand.SetDom2, uid, []]
  }
  const dom = getChatVirtualDom({
    addContextButtonEnabled,
    authEnabled,
    authErrorMessage,
    authStatus,
    chatListScrollTop,
    composerDropActive,
    composerDropEnabled,
    composerFontFamily,
    composerFontSize,
    composerHeight,
    composerLineHeight,
    composerValue,
    listFocusedIndex,
    messagesScrollTop,
    modelPickerOpen,
    modelPickerSearchValue,
    models,
    openApiApiKeyInput,
    openApiApiKeyInputPattern,
    openApiApiKeysSettingsUrl,
    openApiApiKeyState,
    openRouterApiKeyInput,
    openRouterApiKeyState,
    parsedMessages,
    projectExpandedIds,
    projectListScrollTop,
    projects,
    runMode,
    runModePickerOpen,
    searchEnabled,
    searchFieldVisible,
    searchValue,
    selectedModelId,
    selectedProjectId,
    selectedSessionId,
    sessions,
    showRunMode,
    todoListToolEnabled,
    tokensMax,
    tokensUsed,
    usageOverviewEnabled,
    useChatMathWorker,
    viewMode,
    visibleModels,
    voiceDictationEnabled,
  })
  return [ViewletCommand.SetDom2, uid, dom]
}
