import { i18nString } from '@lvce-editor/i18n'

export const chatTitle = i18nString('Chat')
export const chats = i18nString('Chats')
export const newChat = i18nString('New Chat')
export const backToChats = i18nString('Back to chats')
export const settings = i18nString('Settings')
export const closeChat = i18nString('Close Chat')
export const clickToOpenNewChat = i18nString('Click the + button to open a new chat.')
export const startConversation = i18nString('Start a conversation by typing below.')
export const you = i18nString('You')
export const assistant = i18nString('Assistant')
export const composePlaceholder = i18nString('Type your message. Enter to send, Shift+Enter for newline.')
export const sendMessage = i18nString('Send message')
export const send = i18nString('Send')
export const deleteChatSession = i18nString('Delete chat session')
export const defaultSessionTitle = i18nString('Chat 1')
export const dummyChatA = i18nString('Dummy Chat A')
export const dummyChatB = i18nString('Dummy Chat B')
export const dummyChatC = i18nString('Dummy Chat C')